# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Erlymon
email: support@erlymon.org
description: > # this means to ignore newlines until "baseurl:"
  Erlymon is the free and open source GPS tracking system software offers self hosting real time online vehicle fleet management and personal tracking.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://erlymon.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  erlymon

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
